version: '3.8'

services:
  flask-bokeh-app:
    build: .
    container_name: flask-bokeh-portfolio-optimizer
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    volumes:
      - ./outputs:/app/outputs
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-default-dev-key-replace-in-production}
      - PORT=${PORT:-5000}
      - HOST=${HOST:-0.0.0.0}
      - PYTHON_VERSION=${PYTHON_VERSION:-3.10.11}
    restart: unless-stopped
    env_file:
      - .env
